# Backpropagation
## XOR
* 하나의 히든 레이어
* input layer는 2개의 노드 +1개의 바이어스
* hidden layer는 3개의 노드 +1개의 바이어스
* output은 하나의 노드

* X = np.array([[0,0,1],[1,0,1],[0,1,1],[1,1,1]])
* y = np.array([[0],[1],[1],[0]])

위의 데이터를 neural networks에서 backpropagation을 이용하여 학습시켜라

In [1]:
import numpy as np

In [2]:
X = np.array([[0,0,1],[1,0,1],[0,1,1],[1,1,1]]) # 세번째 항은 bias
y = np.array([[0],[1],[1],[0]])

In [3]:
#sigmoid 함수
def f(x):
    return 1/(1+np.exp(-x))
def f_p(x):
    return f(x)*(1-f(x))

In [4]:
#초기값 임의로 지정
w0=np.array([[1,1,1,1],[0,1,0,1],[1,0,1,0]])
w1=np.array([[1],[1],[1],[1]]) #네번째 항은 bias
eta=1

#### 최초 순방향 계산으로 값들 얻기

In [5]:
net_h0=X[0][0]*w0[0][0]+X[0][1]*w0[1][0]+X[0][2]*w0[2][0]
net_h1=X[1][0]*w0[0][1]+X[1][1]*w0[1][1]+X[1][2]*w0[2][1]
net_h2=X[2][0]*w0[0][2]+X[2][1]*w0[1][2]+X[2][2]*w0[2][2]
net_h3=X[3][0]*w0[0][3]+X[3][1]*w0[1][3]+X[3][2]*w0[2][3]
net_h=np.array([[net_h0],[net_h1],[net_h2],[1]]) #최초 net_h의 네번째 항은 bias
net_h

h=f(net_h)
net_h, h

(array([[1],
        [1],
        [1],
        [1]]),
 array([[0.73105858],
        [0.73105858],
        [0.73105858],
        [0.73105858]]))

In [6]:
net_o=h*w1
o=f(net_o)
net_o, o

(array([[0.73105858],
        [0.73105858],
        [0.73105858],
        [0.73105858]]),
 array([[0.67503753],
        [0.67503753],
        [0.67503753],
        [0.67503753]]))

#### Backpropagation

In [7]:
e=o-y
delta_o=e*f_p(net_o)
delta_j=delta_o*w1*f_p(net_h)
delta_o, delta_j

(array([[ 0.14807749],
        [-0.07128437],
        [-0.07128437],
        [ 0.14807749]]),
 array([[ 0.0291138 ],
        [-0.01401536],
        [-0.01401536],
        [ 0.0291138 ]]))

In [8]:
w1=w1-eta*delta_o*h
w0=w0-eta*np.transpose(delta_j*X)
w1, w0, o

(array([[0.89174668],
        [1.05211305],
        [1.05211305],
        [0.89174668]]),
 array([[ 1.        ,  1.01401536,  1.        ,  0.9708862 ],
        [ 0.        ,  1.        ,  0.01401536,  0.9708862 ],
        [ 0.9708862 ,  0.01401536,  1.01401536, -0.0291138 ]]),
 array([[0.67503753],
        [0.67503753],
        [0.67503753],
        [0.67503753]]))

#### 반복

In [10]:
for i in range(10000):
    net_h0=X[0][0]*w0[0][0]+X[0][1]*w0[1][0]+X[0][2]*w0[2][0]
    net_h1=X[1][0]*w0[0][1]+X[1][1]*w0[1][1]+X[1][2]*w0[2][1]
    net_h2=X[2][0]*w0[0][2]+X[2][1]*w0[1][2]+X[2][2]*w0[2][2]
    net_h3=X[3][0]*w0[0][3]+X[3][1]*w0[1][3]+X[3][2]*w0[2][3]
    
    net_h=np.array([[net_h0],[net_h1],[net_h2],[net_h3]])
    h=f(net_h)
    
    net_o=h*w1
    o=f(net_o)
    
    e=o-y
    delta_o=e*f_p(net_o)
    delta_j=delta_o*w1*f_p(net_h)
    
    w1=w1-eta*delta_o*h
    w0=w0-eta*np.transpose(delta_j*X)
    if(e.all()==0):
        break
w0, w1, o

(array([[1.        , 2.1863048 , 1.        , 1.61643243],
        [0.        , 1.        , 1.1863048 , 1.61643243],
        [2.77345073, 1.1863048 , 2.1863048 , 0.61643243]]),
 array([[-5.5965467 ],
        [ 5.46040595],
        [ 5.46040595],
        [-5.3910309 ]]),
 array([[0.00512963],
        [0.99492984],
        [0.99492984],
        [0.0050737 ]]))

#### 실제값 y와 예측값 o가 거의 비슷해졌다.